# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a90ee9088950de797a3ca4fd14dad85dd5d09b42c2b241f73d7ee85844fbcc347981e80f9286a7996d6c3f20ae960a31ac5b8878a4d6e93bb738255e25922532

test:
  secret_key_base: 4b84b4980970c1da22043cb8f0240174b88255e816349036c561d6820df688b595a9d0c2ae2c7ed83de3a777862fdb579856cf93aec7d73b416952b0456e375f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
